apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zweasy3nv-nodejs
  janus-idp.io/tekton: zweasy3nv-nodejs
  backstage.io/kubernetes-id: zweasy3nv-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zweasy3nv-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
