apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zweasy3nv-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zweasy3nv-nodejs 
  name: zweasy3nv-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: zweasy3nv-nodejs 
